jenkins-builder:
  build: ./
  #image: victor755555/jenkins:1.651.3
  privileged: true
  ports:
  - 3001:8080
  #external_links:
  #- convoy-gluster/convoy-gluster:convoy-cluster
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: provider=scaleway
    type: builder
  tty: true
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock 
    - ./jenkins_home/:/var/jenkins_home/
  stdin_open: true
